version: "3.8"

networks:
  streamlitdocker:
    name: streamlitdocker
    driver: bridge

services:
  streamlit:
    image: "streamlit/redux_payroll_mate:${DATE:-latest}"
    container_name: streamlit_redux_PM
    hostname: streamlit_redux_PM
    pull_policy: never
    tty: true
    ports:
      - "8501:8501"
    build:
      context: .
      dockerfile: docker/streamlit_redux/streamlit_redux_payroll.df
    networks:
      - streamlitdocker
    volumes:
      - ".:/app"
